version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: hotels_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  session-service:
    build: ./services/session-service
    container_name: session-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8086:8081"
    depends_on:
      - postgres
    networks:
      - app-network

  hotel-service:
    build: ./services/hotel-service
    container_name: hotel-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8081:8082"
    depends_on:
      - postgres
    networks:
      - app-network

  loyalty-service:
    build: ./services/loyalty-service
    container_name: loyalty-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - app-network

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - app-network

  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_EXCHANGE=booking_exchange
      - RABBIT_MQ_QUEUE_NAME=booking_queue
      - HOTEL_SERVICE_HOST=hotel-service
      - HOTEL_SERVICE_PORT=8082
      - PAYMENT_SERVICE_HOST=payment-service
      - PAYMENT_SERVICE_PORT=8084
      - LOYALTY_SERVICE_HOST=loyalty-service
      - LOYALTY_SERVICE_PORT=8083
    ports:
      - "8082:8083"
    depends_on:
      - postgres
      - rabbitmq
      - hotel-service
      - payment-service
      - loyalty-service
    networks:
      - app-network

  report-service:
    build: ./services/report-service
    container_name: report-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hotels_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_EXCHANGE=booking_exchange
      - RABBIT_MQ_QUEUE_NAME=booking_queue
    ports:
      - "8087:8086"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    environment:
      - SESSION_SERVICE_HOST=session-service
      - SESSION_SERVICE_PORT=8081
      - HOTEL_SERVICE_HOST=hotel-service
      - HOTEL_SERVICE_PORT=8082
      - BOOKING_SERVICE_HOST=booking-service
      - BOOKING_SERVICE_PORT=8083
      - LOYALTY_SERVICE_HOST=loyalty-service
      - LOYALTY_SERVICE_PORT=8085
      - REPORT_SERVICE_HOST=report-service
      - REPORT_SERVICE_PORT=8086
    ports:
      - "8080:8087"
    depends_on:
      - session-service
      - hotel-service
      - booking-service
      - loyalty-service
      - report-service
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge